### ISSUE TITLE
JupyterLite page with anywidget is currently broken.

### ISSUE THREAD

**Issue by kolibril13** [jtpio/anywidget-lite#5]
Hi @jtpio,
I just noted that https://github.com/jtpio/anywidget-lite and the corresponding page https://jtp.io/anywidget-lite/lab/index.html currently throws an error "Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0.11'." 

Would be great to use this page again! 🙂

<img width="713" alt="image" src="https://github.com/user-attachments/assets/1102addc-e98d-477c-b397-05ef83f3947a">

cc. @manzt

**Comment by jtpio** [comment]
Yes, it's the usual issue related to the mock package: https://github.com/jupyterlite/jupyterlite/issues/1342

We should ideally fix this https://github.com/jupyterlite/pyodide-kernel.
