### ISSUE TITLE
Sharing anywidget JupyterLite demos with nblink

### ISSUE THREAD

**Issue by kolibril13** [jtpio/anywidget-lite#7]
It would be great to share anywidget projects with others in jupyterlite using nblink: https://github.com/dwootton/nblink
So that sharing would be as simple as:
https://x.com/kolibril13/status/1811146849291812984

Therefore, I'd like to ask:
 Can this "Save to URL" button be added to this JupyterLite repo?

cc @dwootton @manzt @jtpio

**Comment by jtpio** [comment]
Thanks @kolibril13!

Yes this should definitely be possible, and probably just a matter of adding `nblink` to the list of requirements: https://github.com/jtpio/anywidget-lite/blob/main/requirements.txt. We could also document that in the README.

Would you like to open a PR? Thanks!
